stages:
  - build

build-job: 
  stage: build
  image: python:3.7
  script:
    - echo "Starting Build ......"
    - pip install requests python-gitlab semver
    - cd scripts
    - python -m gen_ver.generate_new_version_file "vesion.h.in" "patch"
    - cat version.h.in
    - ls -l
  rules:
    - when: always
