stages:
  - build

build-job: 
  stage: build
  image: python:3.7
  script:
    - echo "Starting Build ......"
    - pip install requests python-gitlab semver
    - python -m scripts/gen_ver
    - ls -l
  rules:
    - when: always
