stages:
  - build

build-job: 
  stage: build
  image: python:3.7
  script:
    - echo "Starting Build ......"
    - pip install requests python-gitlab semver
    - cd scripts
    - python -c 'from gen_ver import gen_version; gen_version("../version.h.in", "patch")'
    - ls -l
    - cat ../version.h.in
  rules:
    - when: always
